### PR TITLE
decimal: add decomposer interface

### PR DESCRIPTION
**Pull request by kardianos**
For golang/go#30870

### CODE REVIEW

**Comment by kardianos** [comment]
Let me know if you think this interface will work.

**Review by ericlagergren — DISMISSED** [review]

**Comment by kardianos** [comment]
Hi @ericlagergren , could you take another look?

**Comment by ericlagergren** [comment]
It looks good to me! I’ve just been waiting for the green light to merge it :D

**Comment by kardianos** [comment]
You have a green light from me :)
This is merged in two fixed precision packages and coachroachdb/apd.

**Review by ericlagergren — APPROVED** [review]

**Comment by ericlagergren** [comment]
@kardianos how would you like me to list you, if at all, in the CONTRIBUTORS file?

**Comment by kardianos** [comment]
If you want, you could list "Daniel Theophanes <kardianos@gmail.com>".

**Comment by zhongduo** [comment]
@kardianos  @ericlagergren it has been three years since this PR is introduced, is there any plan to fix all the sql drivers etc? Currently it is failing tools like sqlboiler or likely anything without proper driver support. If no one is driving to update those drivers it likely won't happen. If the interest of continuing this work is low, I would suggest to revert this change so people other package can use the latest version. What do you think?

**Pull request merged**
