### PR TITLE
Bug#99. Comparison fails under some conditions

### PR DESCRIPTION
**Pull request by timothyham**
Fixes bug https://github.com/ericlagergren/decimal/issues/99 with unit test.

### CODE REVIEW

**Comment by timothyham** [comment]
I added a new test file because I don't quite know where to place the test into. Can update this PR to put it in the right place.

**Comment by timothyham** [comment]
https://github.com/ericlagergren/decimal/issues/99

**Comment by ericlagergren** [comment]
If you could put the test in `issues_test.go` that would be great. Thank you for the PR and sorry for missing that! 😬

**Comment by timothyham** [comment]
@ericlagergren Ok, the test is in issues_test.go.

**Review by ericlagergren — APPROVED** [review]

**Comment by ericlagergren** [comment]
@timothyham thanks so much!

**Pull request merged**
