### PR TITLE
Add GDA dectest suite 

### PR DESCRIPTION
**Pull request by rdingwall**
Here's my first stab at adding the GDA dectest suite of unit tests: http://speleotrove.com/decimal/dectest.html

24,316 pass
4,147 fail
374 skipped (via `t.Skip()`)
36,258 not run

The not run reasons include:

- operation not implemented
- conditions not implemented
- rounding mode not implemented
- directive not implemented

The skip reasons include: 

- tests which are skipped in libmpdec
- I excluded 313 tests which cause the Go test runner to hang

I couldn't figure out how to implement these operations:

- and
- comparesig
- invert
- nexttoward
- or
- plus
- remaindernear
- rescale
- rotate
- scaleb
- shift
- toEng
- tointegral
- toSci
- trim
- xor 

I've mapped the rounding modes as following (might be incorrect):

- ceiling: to positive inf
- down: to zero
- floor: to negative inf
- half even: to nearest even
- half up: to nearest away

The broad structure is:

- _dectest/*.decTest - test data files
- _dectest/generate.bash - downloads and unzips test data files
- dectest/scanner.rl - stateful scanner using same pattern as bufio.Scanner (required due to directives inserted between tests)
- dectest/case.go - definitions of dectest types
- dectest/test.go - implementation and mapping from dectest to decimal types
- dectest/skip.go - manually skipped tests

The tests are running in Travis CI. To run the tests locally:

```
./_dectest/generate.bash
cd dectest && ./ragel.bash
cd ..
go test --run=TestDecTests -v
```

**Specific feedback wanted:**

1. Have I implemented these tests correctly? (e.g. mapped rounding modes correctly)
2. Are there any other operations that could be supported? (from the list above of operations I couldn't figure out how to implement)
3. Failing tests - what should we do with these? It feels like there will probably be a combination of incorrectly implemented tests, and some genuine bugs. It seems out of scope of this PR to fix all the genuine bugs, so should I mark them as skipped and leave them for future PRs to investigate and fix?
4. Structure - are there any structural changes you would like?
5. Style - are there any style changes you would like?

### CODE REVIEW

**Comment by rdingwall** [comment]
Because each test is run independently via `t.Run()`, I had to disable go test verbose mode in Travis, otherwise it exceeds the Travis maximum job log length and causes the job to terminate. Hopefully this is okay, because go test automatically prints verbose output for any failed  tests.

**Comment by ericlagergren** [comment]
> Have I implemented these tests correctly? (e.g. mapped rounding modes correctly)

I think so! So far, nothing glaring has stood out.

> Are there any other operations that could be supported? (from the list above of operations I couldn't figure out how to implement)

Yeah, `nexttoward` and `plus` are inside `misc/`, I think. `toEng`, `tointegral`, and `toSci` are `Decimal.Format` options.

> Failing tests - what should we do with these? ... It seems out of scope of this PR to fix all the genuine bugs, so should I mark them as skipped and leave them for future PRs to investigate and fix?

Yeah, skip.

> Structure - are there any structural changes you would like? ... Style -  are there any style changes you would like?

To spare you from having to make little nitpick style changes on my behalf, I've created a branch off your PR with some of the styling changes. I'll give you commit permissions so you can change whatever you think is necessary. (See: https://github.com/ericlagergren/decimal/pull/117)

**Comment by ericlagergren** [comment]
Also: @rdingwall how would you like me to mention you inside the AUTHORS file?

**Comment by rdingwall** [comment]
Thanks! The new PR is ready to review now. I implemented `toSci` and made a few tweaks to make Travis happy.

> Yeah, nexttoward and plus are inside misc/, I think

I found (and imlemented) nextplus but couldn't find nexttoward or plus.

> toEng, tointegral, and toSci are Decimal.Format options.

I could only implement `toSci`. `toIntegral` seems to be a version of `RoundToInt()` which isn't supported (it's not a string formatting function). I can't see that engineering notation (where the exponent is a power of three) is supported to implement `toEng`.

> Also: @rdingwall how would you like me to mention you inside the AUTHORS file?

`Richard Dingwall <rdingwall@gmail.com>` please 🙂

**Pull request closed without merging**
