### PR TITLE
Improved comments for Quantize

### LINKED ISSUE #133: Inconsistent comments
https://github.com/ericlagergren/decimal/blob/ac8aeb47a55cc0f667ba2f6ab469753b5b682b22/big.go#L948

The comment to `Quantize` is misleading. You need to set 

> Rounding towards zero
> round towards zero (or truncate, or round away from infinity): y is the integer part of x, without its fraction digits.
https://en.wikipedia.org/wiki/Rounding#Rounding_towards_zero
for the method to behave as Truncate

### PR DESCRIPTION
**Pull request by yarco**
Fixes #133

### CODE REVIEW

**Comment by yarco** [comment]
@ericlagergren a small comment improvement to consider

**Comment by ericlagergren** [comment]
Awesome, thank you!!

**Review by ericlagergren — APPROVED** [review]

**Comment by ericlagergren** [comment]
How would you like me to list you in the CONTRIBUTORS file, if at all?

**Comment by yarco** [comment]
Please use the name specified in my profile, Yarco Hayduk. Thank you!

**Pull request merged**
