### PR TITLE
correctly set form = zero in SetString

### PR DESCRIPTION
**Pull request by madelynnblue**
Also add a function that verifies the zero form is correctly set when
it should be.

### CODE REVIEW

**Comment by madelynnblue** [comment]
Found while doing some other investigations.

**Comment by madelynnblue** [comment]
What are your thoughts about t.Run subtests? They are super useful because of how easy they make formatting the output, but since they don't work in go1.6 the CI fails. Are you ok bumping the CI to use go 1.7? That would make this package untestable on go < 1.7, but I think that's fine.

**Comment by ericlagergren** [comment]
> What are your thoughts about t.Run subtests?

I'm okay with it. Or, alternatively, create a file with a 1.7 build tag to hold off until 1.8 is released. I can't say I have much of a floor for Go versions for this project, however it's typically good form to have compatibility within 1 version of stable.

**Comment by madelynnblue** [comment]
I've split out the new subtest function into a go1.7-tagged file.

**Comment by ericlagergren** [comment]
fantastic. thank you for this PR. much appreciated.

**Comment by ericlagergren** [comment]
closed b/c https://github.com/EricLagergren/decimal/pull/13#issuecomment-265666263

**Pull request closed without merging**
